apiVersion: v1
kind: Service
metadata:
    name: svc-galaxyazuredevopskubernetesclient
    labels:
        product: galaxyazuredevopskubernetesclient
spec:
    selector:
        app: app-galaxyazuredevopskubernetesclient
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-galaxyazuredevopskubernetesclient
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-galaxyazuredevopskubernetesclient
        spec:
            containers:
            - image: appservicesdockerregister.azurecr.io/galaxyazuredevopskubernetesclient:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: galaxyazuredevopskubernetesclient
              ports:
              - containerPort: 80
            imagePullSecrets:
            - name: regsecret